### PR TITLE
Remove bowerDependencies warning

### LINKED ISSUE #433: `bowerDependencies` has been deprecated.
Seeing this deprecation warning after upgrading to `ember-cli@4.3.0`:

```
DEPRECATION: `bowerDependencies` has been deprecated.
If you still need access to the project's Bower dependencies, you will have to manually resolve the project's `bower.json` file instead. [ID: ember-cli.project.bower-dependencies]
at getStackTrace (C:\Users\cfries\Documents\Repositories\brokers\node_modules\ember-cli\lib\debug\deprecate.js:99:15)
at deprecate (C:\Users\cfries\Documents\Repositories\brokers\node_modules\ember-cli\lib\debug\deprecate.js:77:8)
at Project.bowerDependencies (C:\Users\cfries\Documents\Repositories\brokers\node_modules\ember-cli\lib\models\project.js:412:5)
at Class.init (C:\Users\cfries\Documents\Repositories\brokers\node_modules\ember-data-model-fragments\index.js:13:34)
at Class.superWrapper [as init] (C:\Users\cfries\Documents\Repositories\brokers\node_modules\core-object\lib\assign-properties.js:34:20)
at new CoreObject (C:\Users\cfries\Documents\Repositories\brokers\node_modules\core-object\core-object.js:9:15)
at new Class (C:\Users\cfries\Documents\Repositories\brokers\node_modules\core-object\core-object.js:21:5)
at new Class (C:\Users\cfries\Documents\Repositories\brokers\node_modules\core-object\core-object.js:21:5)
at PackageInfo.constructAddonInstance (C:\Users\cfries\Documents\Repositories\brokers\node_modules\ember-cli\lib\models\package-info-cache\package-info.js:480:23)
at PackageInfo.getAddonInstance (C:\Users\cfries\Documents\Repositories\brokers\node_modules\ember-cli\lib\models\package-info-cache\package-info.js:522:28)
```

https://github.com/adopted-ember-addons/ember-data-model-fragments/blob/310ad1a4587e4ff5a913a6a40c79cd8f32670da1/index.js#L13

### PR DESCRIPTION
**Pull request by charlesfries**
Fixes #433

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -7,22 +7,6 @@ const calculateCacheKeyForTree = require('calculate-cache-key-for-tree');
 module.exports = {
   name: require('./package').name,
 
-  init() {
```
Comment (charlesfries) [inline index.js:10]: Is it okay to remove this function entirely?
